### ISSUE TITLE
Publish on F-Droid

### ISSUE THREAD

**Issue by Bubu** [benjaminSchilling33/congress_fahrplan#4]
> * [ ] The original app author has been notified (and supports the inclusion).

What do you say?

See the request for packaging here: https://gitlab.com/fdroid/rfp/issues/1176

**Comment by benjaminSchilling33** [comment]
Great idea which is on my agenda for some time already, but I have to admit that I'm not familiar with F-Droid.
What are the next steps?

**Comment by Bubu** [comment]
Someone will hopefully package it before congress. I'm currently a bit busy, If you want to take a look, here is the build recipe file of another flutter app: https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/im.pattle.app.yml#L86

**Comment by IzzySoft** [comment]
It would be great if you could add [Fastlane file structure](https://gitlab.com/snippets/1895688) to your repo, to provide screenshots (and also a more detailed description). Further, we currently cannot provide auto-update (or even an appropriate update check) as you [use variables/function-calls for `versionCode` and `versionName`](https://github.com/benjaminSchilling33/congress_fahrplan/blob/1.0.14/android/app/build.gradle#L44) – our scanner only performs RegEx matching on the `build.gradle`, it doesn't "execute" gradle. Thanks!

**Comment by Bubu** [comment]
Mmh, versioning seems a bit broken. There's a 1.0.14 tag, it encodes a versionname of 1.0.13 here: https://github.com/benjaminSchilling33/congress_fahrplan/blob/master/android/app/build.gradle#L21 and VC 13.

But then flutter sets versionname to 1.0.0 from pubspec.yaml and that gets used in for the android build.

**Comment by Bubu** [comment]
I've now added it here: https://fdroid.gitlab.io/ccc/ as version 1.0.0
It might still make it in time to the main f-droid repo, but I'm not sure.

**Comment by Bubu** [comment]
Updates will need to be added to the F-Droid metadata file manually for now, so please ping me, if there's an update that's important during congress :)

**Comment by benjaminSchilling33** [comment]
> 
> 
> Mmh, versioning seems a bit broken. There's a 1.0.14 tag, it encodes a versionname of 1.0.13 here: https://github.com/benjaminSchilling33/congress_fahrplan/blob/master/android/app/build.gradle#L21 and VC 13.

You got me, I was a little to fast with tagging, missed the commit which increases the version number.

I will keep you updated.

**Comment by benjaminSchilling33** [comment]
@IzzySoft I added the Fastlane File Structure
@Bubu I removed the variables in build.gradle since they where coming from the flutter template project and useless for this case

See https://github.com/benjaminSchilling33/congress_fahrplan/pull/5

**Comment by IzzySoft** [comment]
> I added the Fastlane File Structure

Thanks! But it's not visible in master – nor is it behind the tag. F-Droid needs it reachable from the tag. So could you either merge that branch – or point the tag to a commit inside it?

**Comment by benjaminSchilling33** [comment]
Sure, just wanted to make sure it's correct before merging

**Comment by IzzySoft** [comment]
Good idea. So explicitly: LGTM :smile:

**Comment by benjaminSchilling33** [comment]
The new version is merged and tagged: 1.0.15

If it works for F-Droid I would close this issue.

**Comment by IzzySoft** [comment]
@Bubu will you try packaging it then? Or ping another packager if you lack the time?

**Comment by Bubu** [comment]
Done.
