### ISSUE TITLE
Fahrplan nicht mehr verfügbar! 

### ISSUE THREAD

**Issue by andreasb242** [benjaminSchilling33/congress_fahrplan#6]
Die App lädt ewig, nach Daten löschen:
"Fahrplan not yet Released!" und startet nicht mehr.

**Comment by benjaminSchilling33** [comment]
@andreasb242 danke für die Info, bei vielen anderen treten die Probleme nicht auf, ich hab aber schon einige Punkte identifiziert die bis zum nächsten Jahr überarbeitet werden. Damit sollte auch dein Problem gelöst werden.

**Comment by benjaminSchilling33** [comment]
@andreasb242 siehe Version 1.0.16

**Comment by andreasb242** [comment]
Besten Dank. Wirklich testen werde ich wohl nächstes Jahr ;-)
Aktuell lädt die App die Daten wieder, ich habe aber kein Update eingespielt.
Der Fehler ist übriges nicht nur bei mir aufgetreten, sondern auch bei einem Kollegen, darum habe ich einen Bug erfasst.
