### ISSUE TITLE
Datum / Wochentag ist falsch zugeordnet

### ISSUE THREAD

**Issue by der-den** [benjaminSchilling33/congress_fahrplan#9]
In der App steht oben Sonntag bis Mittwoch. Korrekt ist aber Montag bis Donnerstag.

**Comment by benjaminSchilling33** [comment]
Ich habe erst vor 2h angefangen die App für dieses Jahr anzupassen.
Daher passen die Tage bisher nicht, da noch der Fahrplan vom letzten Jahr verwendet wird. 
Leider wurde diese App ohne Abstimmung im CCC Event Blog erwähnt, ich hatte bisher aus Zeitgründen kein Update für dieses Jahr geplant.

**Comment by der-den** [comment]
Ich hattes mir später schon so gedacht. Naja, so schnell ist man im Boot :-)
